// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: model/tunnel.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	FromAddress string `protobuf:"bytes,2,opt,name=fromAddress,proto3" json:"fromAddress,omitempty"`
	ToAddress   string `protobuf:"bytes,3,opt,name=toAddress,proto3" json:"toAddress,omitempty"`
}

func (x *TunnelOpen) Reset() {
	*x = TunnelOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_tunnel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelOpen) ProtoMessage() {}

func (x *TunnelOpen) ProtoReflect() protoreflect.Message {
	mi := &file_model_tunnel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelOpen.ProtoReflect.Descriptor instead.
func (*TunnelOpen) Descriptor() ([]byte, []int) {
	return file_model_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelOpen) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TunnelOpen) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TunnelOpen) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

type TunnelOpenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TunnelOpenResponse) Reset() {
	*x = TunnelOpenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_tunnel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TunnelOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelOpenResponse) ProtoMessage() {}

func (x *TunnelOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_tunnel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelOpenResponse.ProtoReflect.Descriptor instead.
func (*TunnelOpenResponse) Descriptor() ([]byte, []int) {
	return file_model_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelOpenResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *TunnelOpenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_model_tunnel_proto protoreflect.FileDescriptor

var file_model_tunnel_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x60, 0x0a, 0x0a, 0x54,
	0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x46, 0x0a,
	0x12, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_tunnel_proto_rawDescOnce sync.Once
	file_model_tunnel_proto_rawDescData = file_model_tunnel_proto_rawDesc
)

func file_model_tunnel_proto_rawDescGZIP() []byte {
	file_model_tunnel_proto_rawDescOnce.Do(func() {
		file_model_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_tunnel_proto_rawDescData)
	})
	return file_model_tunnel_proto_rawDescData
}

var file_model_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_tunnel_proto_goTypes = []interface{}{
	(*TunnelOpen)(nil),         // 0: model.TunnelOpen
	(*TunnelOpenResponse)(nil), // 1: model.TunnelOpenResponse
}
var file_model_tunnel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_tunnel_proto_init() }
func file_model_tunnel_proto_init() {
	if File_model_tunnel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_tunnel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_tunnel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TunnelOpenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_tunnel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_tunnel_proto_goTypes,
		DependencyIndexes: file_model_tunnel_proto_depIdxs,
		MessageInfos:      file_model_tunnel_proto_msgTypes,
	}.Build()
	File_model_tunnel_proto = out.File
	file_model_tunnel_proto_rawDesc = nil
	file_model_tunnel_proto_goTypes = nil
	file_model_tunnel_proto_depIdxs = nil
}
